### ISSUE TITLE
data alignment

### ISSUE THREAD

**Issue by rjbudzynski** [ayonious/console-table-printer#10]
It would be a nice feature if one could control alignment (left/right/center) of data within the cells - by column, say.

**Comment by rjbudzynski** [comment]
Okay, so after a closer look I get that I can control alignment by creating a Table instance with hand-configured columns. I was using the printTable() api which doesn't seem to allow for control of alignment. But maybe some way could be invented to have it there, too.

**Comment by ayonious** [comment]
@rjbudzynski could you point out what would be best way to define the function? There is a way I can expose another function(or same!) to provide what you are looking for but then the input will look something like this:

`
{
rows:
[
    {
        text: {
            name: 'adsf'
            age: '12'
        }
    }.
    {
        text: {
            name: 'adsf'
            age: '12'
        }
    }
]
columns:
[
    {
        alignment: 'left',
        name: 'name'
    },
    {
        alignment: 'left',
        name: 'age'
    }
]
}
`

What do you think? Does it look like a simple input that you can pass? I want to keep the library as simple(or user friendly) possible. But Im still thinking about whats the best way to make it easy for users to use it without going into deep documentation to understand how to configure so many fields.

**Comment by ayonious** [comment]
It has been too long and no one else asked for this feature. 
And also no clear structure for solution.
Closing the Issue
