### ISSUE TITLE
where did the zeros go?

### ISSUE THREAD

**Issue by nova76** [ayonious/console-table-printer#142]
Hi.
In this case:
            const p = new Table();
            p.addRows([{index:0, value:0}, {index:1, value:1}]);  
            p.printTable();

this is the result (node.js v10.16.0)
╔═══════╦═══════╗
║ index         ║ value        ║
╟═══════╬═══════╢
║                   ║                 ║
║     1            ║     1          ║
╚═══════╩═══════╝

where did the zeros go?

**Comment by ayonious** [comment]
Fixed this issue in https://github.com/ayonious/console-table-printer/pull/144
Version 1.4.16
