### ISSUE TITLE
Render to string

### ISSUE THREAD

**Issue by elderapo** [ayonious/console-table-printer#245]
Is it possible to render a table to string instead of the console? I'd like to render the table to string and send it over the wire to be rendered somewhere else.

**Comment by arifkalayci** [comment]
I need to do something similar too. Looking at the code, I found out that the table is printed to the global `console` object. Something like this seems to work but hacky:

```
const { StringDecoder } = require('string_decoder');

class StringWritable extends stream.Writable {
  constructor(options) {
    super(options);
    this._decoder = new StringDecoder(options && options.defaultEncoding);
    this.data = '';
  }
  _write(chunk, encoding, callback) {
    if (encoding === 'buffer') {
      chunk = this._decoder.write(chunk);
    }
    this.data += chunk;
    callback();
  }
  _final(callback) {
    this.data += this._decoder.end();
    callback();
  }
}

const { printTable } = require("console-table-printer");

const testCases = [
  { index: 3, text: "I would like some gelb bananen bitte", value: 100 },
  { index: 4, text: "I hope batch update is working", value: 300 },
];

const { Console } = require('console');

// Save present console in a variable
const oldConsole = console;

// Create a new console which will print to a string and override 'console' global
const stream = new StringWritable();
console = new Console(stream);

printTable(testCases);

// Get old console back
console = oldConsole;

console.log(stream.data);
```

What I want to do is to print to a remote console. Overriding global `console` works, but in general it's desirable that the library accepts a custom console.

**Comment by ayonious** [comment]
There is already an internal functiona that I can expose that can help in this case.
Take a look at this.
https://github.com/ayonious/console-table-printer/blob/master/test/internalTable/simpleTable.test.ts#L14

Instead putting the output in console in returns array of string 

`
[
      '┌───────┬──────────────────────────────────────┬───────┐',
      '\u001b[37m│\u001b[0m\u001b[37m \u001b[0m\u001b[01mindex\u001b[0m\u001b[37m │\u001b[0m\u001b[37m \u001b[0m\u001b[01m                                text\u001b[0m\u001b[37m │\u001b[0m\u001b[37m \u001b[0m\u001b[01mvalue\u001b[0m\u001b[37m │\u001b[0m',
      '├───────┼──────────────────────────────────────┼───────┤',
      '\u001b[37m│\u001b[0m\u001b[37m \u001b[0m\u001b[37m    3\u001b[0m\u001b[37m │\u001b[0m\u001b[37m \u001b[0m\u001b[37mI would like some gelb bananen bitte\u001b[0m\u001b[37m │\u001b[0m\u001b[37m \u001b[0m\u001b[37m  100\u001b[0m\u001b[37m │\u001b[0m',
      '\u001b[37m│\u001b[0m\u001b[37m \u001b[0m\u001b[37m    4\u001b[0m\u001b[37m │\u001b[0m\u001b[37m \u001b[0m\u001b[37m      I hope batch update is working\u001b[0m\u001b[37m │\u001b[0m\u001b[37m \u001b[0m\u001b[37m  300\u001b[0m\u001b[37m │\u001b[0m',
      '└───────┴──────────────────────────────────────┴───────┘',
];
`

My idea was you are supposed to console.log(or your custom logger) each element on this array. Make sure to put an endline after each logging.

So you will use it something like this
```
const t = new Table()
const ret = t.getConsoleLogs(); // array of string
// now use ret to output whereever you want
```
Does this sound good @elderapo @arifkalayci ?

**Comment by elderapo** [comment]
I'd suggest naming that method `render` and just return a single `string` (unless there is a reason why `string[]` would be better).

**Comment by ayonious** [comment]
a new function `render` has been exposed from version 2.4.0

**Comment by cncshaggy** [comment]
Fantastic! I just stumbled upon this update and was able to `2.2` -> `2.4` in my project seamlessly.  

Now instead of clobbering the console in place,
```
this.context.stdout.write("thing");
this._table.printTable(); // x_x
this.context.stdout.write("other thing");
```
 I can now elegantly...
```
this.context.stdout.write("thing");
this.context.stdout.write(this._table.render()); // ^_^
this.context.stdout.write("other thing");
```
🍻 Huzzah!

**Comment by cncshaggy** [comment]
Wow, you literally _just_ did this... 😆
