### ISSUE TITLE
request: include release artifacts & tags

### ISSUE THREAD

**Issue by brettswift** [ayonious/console-table-printer#264]
Hi, 

Thanks for writing this - we quite like it. 

I noticed a bunch of new versions, but there isn't a changelog, nor tags on the repo mapping back to the NPM package. 

Just some friendly feedback for users - it would be great if we could see a change log file or at least tags on the repo that match the npm artifacts.   We actually use this in a cli app that we share with 50+ people so it would be nice to  make the upgrade path a little easier. 

I've found using commitizen and standard-version packages make this quite a nice experience - if you were looking for a suggestion.  

Anyways, thanks again for publishing this!

**Comment by ayonious** [comment]
Thanks for the suggestion @brettswift. I will look into these tools.

For now only way to backtrack the sourcecode to npm version is to look for that commit in master that changed "version" field of package.json. And the changelog is actually the commit message of each commit in master. 
This is not super friendly if you want to automate things but still changes are backtrackable if its necessary.

**Comment by brettswift** [comment]
Thanks for the tip!

**Comment by ayonious** [comment]
@brettswift Added semantic release feature during deployment.

Now you have: 
1. Version Tags in Github with each release
2. CHANGELOG.md
3. Releases with notes (https://github.com/ayonious/console-table-printer/releases)


**NOTE** 
For Older Versions there is no CHANGELOG. This is enabled only for all releases from version 2.5.0

**Comment by brettswift** [comment]
That's awesome.  Thanks!
