### ISSUE TITLE
How to format Dates with printTable ?

### ISSUE THREAD

**Issue by ilanl** [ayonious/console-table-printer#339]
I have an array that have some Dates props,

Can we print the table with a specific date format? Any configuration ?

Thanks, the fact that I'm able to print the table is already awesome, thank you guys!

**Comment by ayonious** [comment]
@ilanl take a look at Computed Columns docs
https://console-table.netlify.app/docs/doc-computed-function

You can write your own function to convert any column to anything else

```
const { Table } = require('console-table-printer');

const t = new Table({
  columns: [
    { name: 'column1' },
    { name: 'column2'},
    { name: 'column3' },
  ],
  computedColumns: [
    {
      name: "format1",
      function: (row) => new Date(row.column3).toUTCString().substr(0, 16),
    },
    {
      name: "format2",
      function: (row) => new Date(row.column3).toLocaleDateString(),
    },
  ]
});

t.addRow({ column1: 1, column2: 'red wine', column3: '2012-11-10' });
t.addRow({ column1: 2, column2: 'very very red wine', column3: '2020-02-24' });
t.addRow({
  column1: 3,
  column2: 'red wine and some stuffs',
  column3: '1990-01-10',
});

t.printTable();
```

The output is 

![dateFormat_js_—_my-npm-packages-tester](https://user-images.githubusercontent.com/19285393/104067758-0b6d6e80-5204-11eb-80cb-6dcf1aea7c40.png)

If this does not help your case please give an example and your expectation

**Comment by ayonious** [comment]
Closing this question for now as its been inactive for more than a week now. @ilanl if you still think there is issue/question feel free to open this again
