### ISSUE TITLE
Colouring entire row or a particular cell on basis some condition 

### ISSUE THREAD

**Issue by Sonivaibhav26** [ayonious/console-table-printer#342]
For example, if I want to color a particular cell if the user has a score >x and different when the score is <x.

**Comment by ayonious** [comment]
There is already a feature called Calculated Columns:
https://console-table.netlify.app/docs/doc-computed-function

<img width="579" alt="fish__Users_nahiyankamal_Desktop_ayonious_my-npm-packages-tester" src="https://user-images.githubusercontent.com/19285393/110213161-21fc1300-7e9f-11eb-99bc-4f6e06c42ec5.png">

**Comment by ayonious** [comment]
@Sonivaibhav26 

There is already a feature called Calculated Columns:
https://console-table.netlify.app/docs/doc-computed-function

<img width="579" alt="fish__Users_nahiyankamal_Desktop_ayonious_my-npm-packages-tester" src="https://user-images.githubusercontent.com/19285393/110213198-3d671e00-7e9f-11eb-8bbd-09d3efa0e28a.png">

**Comment by ayonious** [comment]
@Sonivaibhav26 closing this question assuming this already helped you. Feel free to reopen it if needed
