### ISSUE TITLE
Option for minColSize

### ISSUE THREAD

**Issue by netsmertia** [ayonious/console-table-printer#361]
Hi, 
I am trying to implement a dotmatrix print functionality for invoice generated by web application in browser and by default browser send the HTML as bitmap to printer and dotmatrix printer are not good in bitmap/image printing. 

As it is an invoice on pre-printed stationery and columns width is fixed, I need to provide min column width or you can say fixed width column.

Another enhancement is to print a table without column header.

Thanks.

**Comment by ayonious** [comment]
Thanks @netsmertia both are good ideas.

**Comment by ayonious** [comment]
Since its 2 features, starting a new issue for Table without Header https://github.com/ayonious/console-table-printer/issues/364

**Comment by ayonious** [comment]
From version 2.9.0 This **minLen** param for each column is supported.

https://console-table.netlify.app/docs/doc-limit-line-width
