### ISSUE TITLE
Print table without Table Header

### ISSUE THREAD

**Issue by ayonious** [ayonious/console-table-printer#364]
Originally started from this:
https://github.com/ayonious/console-table-printer/issues/361

Im trying to find the best way to allow this.
How would the input in this case look like? Should it be array or arrays of string?

**Comment by netsmertia** [comment]
I think passing Title value blank or null in column definition would be best. Or having a config array to Table constructor with `headers: false`. 

Another config I am thinking of is `border: false` to print table without borders.

**Comment by ayonious** [comment]
Using something like this should mean that the table has empty headers:
```
const table = new Table({
      title: 'Bundle (BUNDLENAME)',
      columns: [
        { name: 'Weapon', title: 'WEWWWW' },
        { name: 'Chroma', title: 'WEWWWW' },
        { name: 'Quality', title: '' },
        { name: 'Price' },
      ]
    });
```

Now working making it work.

**Comment by ayonious** [comment]
> Another config I am thinking of is border: false to print table without borders.
You should also be able to achieve this using the border symbols set to '' Like this

```
const table = new Table({
      title: 'Bundle (BUNDLENAME)',
      columns: [
        { name: 'Weapon', title: 'WEWWWW' },
        { name: 'Chroma', title: 'WEWWWW' },
        { name: 'Quality', title: '' },
        { name: 'Price' },
      ],
      charLength: { '👍': 2, '✅': 2 },
      style: {
        headerTop: {
          left: '',
          mid: '',
          right: '',
          other: '',
        },
        headerBottom: {
          left: '',
          mid: '',
          right: '',
          other: '',
        },
        tableBottom: {
          left: '',
          mid: '',
          right: '',
          other: '',
        },
        vertical: '',
      },
    });

    table.addRows([
      {
        Weapon: '👍',
        Chroma: '✅',
        Quality: 'Deluxe',
        Price: '1 11 VP',
      },
      {
        Weapon: 'thing',
        Chroma: 'some',
        Quality: 'Deluxe',
        Price: '1 123 VP',
      },
      {
        Weapon: 'asdfasdf',
        Chroma: 'asfasdf',
        Quality: 'Deluxe',
        Price: '1 1000 PP',
      },
    ]);
```


<img width="432" alt="__D_a_my-npm-packages-tester-ts" src="https://github.com/ayonious/console-table-printer/assets/19285393/7ec77fd8-5385-45d4-9f42-911703a02cb0">

**Comment by ayonious** [comment]
In latest release this case has been handled
![__D_a_console-table-printer](https://github.com/ayonious/console-table-printer/assets/19285393/21bca441-f3ef-47f3-b860-5bdf214b40cf)
