### ISSUE TITLE
Letters other than English break the table

### ISSUE THREAD

**Issue by koren-gershoni** [ayonious/console-table-printer#414]
![image](https://user-images.githubusercontent.com/57925934/152646494-e05b5af6-236e-4ec8-8704-8f6e6a2daa85.png)

any way to fix it or making the column bigger than the text?

**Comment by ayonious** [comment]
@koren-gershoni this is supposed to work. Here One test I did worked can you share your code for this?

<img width="502" alt="fish__Users_nahiyankamal_Desktop_ayonious_console-table-printer" src="https://user-images.githubusercontent.com/19285393/156019870-c93466b5-250a-418f-a221-d39eabf80866.png">

**Comment by ayonious** [comment]
No more updates on this will close it for now.
