### ISSUE TITLE
Horizontal and vertical lines are colored differently

### ISSUE THREAD

**Issue by markg85** [ayonious/console-table-printer#427]
![image](https://user-images.githubusercontent.com/49061/180267353-ac55df19-e52f-44b0-b2ae-e1b8103e6e37.png)

The image shows it quite clearly.
It looks like horizontal lines are drawn in the default color and vertical lines are drawn in white.
That looks a bit weird imho.

**Comment by ayonious** [comment]
That is really weird. I see this happening only in some Terminals. This looks really weird. Thanks for reporting @markg85

**Comment by markg85** [comment]
Note that you actually see this in one of your examples too!
![Screenshot](https://cdn.jsdelivr.net/gh/ayonious/console-table-printer@master/static-resources/screenshot-column-props-2.png)

You barely see it due to the color theme the console uses, but you see it if you look very carefully. Perhaps that helps :)

**Comment by ayonious** [comment]
You are right! I changed the color of my terminal and now I can see this more clearly!

I tested on old version. This was there from the beginning!

**Comment by markg85** [comment]
Glad you can reproduce it!
I did look at it but the structure is a bit vague to me. From what i could figure out (which might still be wrong on my part) the horizontal lines are added in their default colors, the vertical lines are added with a specific color.

But i suppose you can figure it out much more quickly as the author of this neat package :)

**Comment by ayonious** [comment]
You are welcome to make a neat PR :)

**Comment by markg85** [comment]
Nice try, hehe. I leave that in your capable hands. I only "guessed" how it looks to be working but i didn't see a way to fix it without diving in.

**Comment by markg85** [comment]
Wooooohooo!! Nice, that's fast!
And a huge commit for a seemingly small issue ;)

Any spoiler on when you release an updated NPM package with this fix?

**Comment by markg85** [comment]
Just tried it locally (yarn build and copy that over my existing install of this package). It looks just as i would expect it. Borders with a single color! Sweet!

But... What if i want to give the borders a different color? How do i do that?

**Comment by ayonious** [comment]
I think this is what your are looking for. 
https://console-table.netlify.app/docs/doc-border-design

**Comment by markg85** [comment]
Yep! Thank you!

**Comment by ayonious** [comment]
released on 2.11.1
