### ISSUE TITLE
[feature] new colors (orange)

### ISSUE THREAD

**Issue by dawadam** [ayonious/console-table-printer#447]
Why no add common colors ?
Like "orange" :
const orange_color: COLOR = "orange";

**Comment by ayonious** [comment]
You can define your own custom colors like this
https://goeuro.slack.com/archives/CH5TE8FQU/p1679908986968379

If you want to have it as default thats also possible. Open for PRs

**Comment by ayonious** [comment]
You can define your own colors:
https://console-table.netlify.app/docs/doc-color#custom-color

Adding this in existing color is also possible. Feel free to open PR

**Comment by ayonious** [comment]
Closing as seems like custom colors can be added
