### ISSUE TITLE
Crimson color doesn't apply to the table

### ISSUE THREAD

**Issue by capiet** [ayonious/console-table-printer#448]
Hello. Creating tables with crimson color theme doesn't work properly. Here is an example of code.
```javascript
import { Table } from 'console-table-printer';

const p = new Table().addRows(
  [
    { index: 1, text: "crimson color text", value: 100 },
    { index: 2, text: "crimson color text", value: 200 },
  ],
  { color: "crimson" } 
);

p.printTable();
```
![изображение](https://github.com/ayonious/console-table-printer/assets/79054211/f98f4944-9205-4ab5-951d-6edfbdc112ed)

**Comment by ayonious** [comment]
It seems like not one of the default colors to be used. I would rather remove it from default list. In case needed try the customColor mapping.

**Comment by ayonious** [comment]
Removed the color in latest version
