### ISSUE TITLE
Provide option to color column or cell color

### ISSUE THREAD

**Issue by vimalraj-a** [ayonious/console-table-printer#57]
Currently all text shown in white color. I would like to keep different color for number.

Cell text with different colors are breaking (Cell colored with `chalk`)

![image](https://user-images.githubusercontent.com/13977942/70385141-3a863080-19b1-11ea-9eb1-840c28f7bf77.png)

**Comment by ffMathy** [comment]
I could use this as well.

**Comment by ayonious** [comment]
In relase 1.2.1 this feature is included.

Here is a sample code how you can do this:
```
new Table({
  style: 'fatBorder', //style of border of the table
  columns: [
    { name: 'column1', alignment: 'left', color: 'red' }, //with alignment and color
    { name: 'column2', alignment: 'right' },
    { name: 'column3' },
  ],
});
```

In case you have color mentioned in both column and row column color will be priotized.
