### ISSUE TITLE
Convenience method like `console.table`?

### ISSUE THREAD

**Issue by flotwig** [ayonious/console-table-printer#7]
Yo,

Nice tool! I've been using it to spice up some performance testing output, and it seems to work well.

It'd be great if there was a convenience method that matches the API of [`console.table`](https://devdocs.io/node/console#console_console_table_tabulardata_properties), so instead of having to do...

```js
  const t = new Table()
  t.addRows(TEST_CASES)
  t.printTable()
```

You could just do...

```js
Table.printTable(TEST_CASES)
```

**Comment by ayonious** [comment]
Closing the issue, Just added a feature(1.0.0-beta13) to print without creating table instance
