### ISSUE TITLE
Sort by column names

### ISSUE THREAD

**Issue by shimphillip** [ayonious/console-table-printer#98]
Thanks for the library.

Can you add a feature where the table is sorted by column names and enable passing in something like 'ASC' or 'DESC' and also by defined column header names I pass?

**Comment by ayonious** [comment]
@shimphillip That sounds like a good idea. I can make it as simple as just passing a new param for each column like this:

```
const p = new Table({
  columns: [
    { name: 'index', sorting_order: 'ASC' }, 
    { name: 'text', alignment: 'right' },
  ],
});
```

But then Im thinking what if you also want to sort by multiple columns. So in that can a generalized api param would be


```
const p = new Table({
  columns: [
    { name: 'index' }, 
    { name: 'text', alignment: 'right' },
  ],
 sorting_order: (row1,row2) => { return row1.index > row2.index; }
});
```

What do you think? Does it look complicated? Or should I allow both?

**Comment by shimphillip** [comment]
Both would be perfect!

**Comment by ayonious** [comment]
created feature for sort and filter. in Version 1.4.0
https://github.com/ayonious/console-table-printer/pull/127


```
new Table({
  style: 'fatBorder', //style of border of the table, (optional)default = thinBorder
  columns: [
    { name: 'column1', alignment: 'left', color: 'red' }, //with alignment and color
    { name: 'column2', alignment: 'right' },
    { name: 'column3' },
  ],
  sort: (row1, row2) => row1.index > row2.index // sorting order of rows (optional)
  filter: (row) => row.index <10 // filtering rows (optional)
});
```
